name: flutter_clb_tinhban_ui_app
description: Mạng xã hội CLB Tình bạn
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"
module:
  androidX: true // Add this line.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  outline_material_icons: ^0.1.0  # https://pub.dev/packages/outline_material_icons  // https://material.io/resources/icons/?style=baseline
  timeago: ^2.0.14  # https://pub.dev/packages/timeago
  carousel_slider: ^1.3.0 # https://pub.dev/packages/carousel_slider
  flutter_launcher_icons: ^0.7.3
  emoji_picker: ^0.1.0
  scrolling_page_indicator: ^0.1.2
  camera: ^0.5.7+4
  path_provider: ^1.6.5
  video_player: ^0.10.8+1
  mime: ^0.9.6+3
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  equatable: ^1.1.1
  file_picker: ^1.5.0+2
  storage_path: ^0.2.0
  transparent_image: any
  image_gallery: ^1.2.0
  multi_image_picker: ^4.6.5+rc.1
  geocoder: ^0.2.1
  location: ^3.0.0
  flutter_staggered_grid_view: ^0.3.0
  photo_manager: ^0.5.0
  photo_view: ^0.9.2
  form_field_validator: ^1.0.0+1 # Kiểm tra emal, có đúng không ( kèm vài thứ khác)
  google_sign_in: ^4.3.0
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.4+2
  firebase_dynamic_links: ^0.5.0+11
  flutter_image_compress: ^0.6.5+1
  flutter_staggered_animations: ^0.1.2
  sqflite: ^1.3.0
  progressive_image: ^1.0.1
  alphabet_list_scroll_view: ^1.0.6
  flutter_slidable: ^0.5.4
  flutter_facebook_login: ^3.0.0
  flutter_video_compress: ^0.3.7+8
  flutter_downloader: ^1.4.1
  video_thumbnail: ^0.2.0
  cached_network_image: ^2.0.0
  #flushbar: ^1.10.0
  esys_flutter_share: ^1.0.2
  infinite_listview: ^1.0.1+1
  chewie: ^0.9.10
  downloads_path_provider: ^0.1.0
  mockito: ^4.1.1
  google_fonts: ^0.3.10
  like_button: ^0.2.0
  image_picker: ^0.6.5
  datetime_picker_formfield: ^1.0.0
  flutter_screenutil: ^1.1.0 # dùng để điều chỉnh kích thước màn hình và font chữ. để giao diện người dùng hiển thị hợp lý trên các kích thước manh hình khác nhau
dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/Butterfly-209.mp4
    - assets/launcher/
    - assets/video/
    - assets/fonts/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

